---
title: "Awards"
---

<link rel="stylesheet" href="styles.css" type="text/css">


##### Top Paper
* Top Student Paper Award, the 71st International Communication Association (ICA) Conference, Political Communication Division (First author, 2021)
* Top Student Paper Award, the 71st ICA Conference, Communication & Technology Division (Co-author, 2021)
* Top Student Paper Award, the 68th ICA Conference, Public Diplomacy Interest Group (Solo author, 2018)
* Top Student Paper Award, the 68th ICA Conference, Visual Communication Studies (First author, 2018) 
* Top Paper Award in Open Call Competition, Association for Education in Journalism and Mass Communication (AEJMC) Conference, Communication Theory & Methodology Division (Co-author, 2018)

##### Academic Awards 
* Chevening Scholarship, the British Foreign and Commonwealth Office, £28,000 (2014)
  
##### Fellowships
* International Institute Individual Fellowship, University of Michigan (2018)
* Lieberthal-Rogel Travel and Research Fellowship, University of Michigan (2018)

##### Research and Travel Grants
* Research Grant, Summer Research Scholars (SRS) program, Duke Kunshan University, ￥25,600 (2022)
* Research Grant, the Center for the Study of Contemporary China (CSCC) at Duke Kunshan University, $2,000 (2021)
* Research Grants, Duke Kunshan University, ￥70,000 (2021)
* Graduate Student Research Grant, the Weiser Center for Emerging Democracies, University of Michigan, $2,500 (2019)
* Graduate Travel Scholarship, University of Michigan, $800 (2019)
* American Council of Learned Societies Predissertation-Summer Travel Grant, $5,000 (2018)
* Graduate Travel Scholarship, University of Michigan, $1,500 (2018)
* Rackham Conference Travel Grant, University of Michigan, $1,000 (2018)
* Conference Travel Grant, Freie Universität Berlin, €1,300 (2018)
* Volkswagen Foundation for Computational Method Workshop, €700 (2018)
* Rackham Conference Travel Grant, University of Michigan, $800 (2017)
